- id: doi:10.1007/s10827-022-00819-7
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2022-02-6
  image: https://link.springer.com/article/10.1007/s10827-022-00819-7/figures/5
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/BioDatanamics-Lab/impedance_input_dependent
    - type: website
      link: https://link.springer.com/article/10.1007/s10827-022-00819-7
  tags:
    - Neuronal response 
    - Rhythms
    - Neuronal irregularities
    - Resonance
    - Piecewise constant inputs
